title:            Ocean Ship
tagline:          Making waves
description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url: http://www.oceanshipgames.com

# Owner/author information
owner:
  name:           Ocean Ship
  avatar:         logo_square.png
  bio:            ""
  email:          staff@patchwack.com
  twitter:        
  github:         oceanship      
  instagram:         
  dribbble:       
  disqus:         
  location:       "Brussels, Belgium"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Brussels
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
